version: '3.7'

services:
  web:
    image: nginx:alpine
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./conf.d:/etc/nginx/config.d:ro
    ports:
      - 80:80
    expose:
      - 80
